version: '3'

services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: nginx-lan
        restart: unless-stopped
        volumes:
          - "/var/run/docker.sock:/tmp/docker.sock:ro"
        ports: 
            - 80:80
        networks:
            - network-nginx-lan

networks:
    network-nginx-lan:
        external:
            name: network-nginx-lan