version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'events-rabbitmq'
    restart: unless-stopped
    environment: 
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PORT: "15672"
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - storage-rabbitmq:/var/lib/rabbitmq/
        - ./log:/var/log/rabbitmq
    networks:
      - network-nginx-lan
      - network-events
    expose:
      - "15672"
networks:
  network-nginx-lan:
    external:
      name: network-nginx-lan
  network-events:
    external:
      name: network-events
volumes:
  storage-rabbitmq: